(venv) ubuntu@ip-172-26-9-152:~/deulbada_BE$ sudo tail -n 50 /var/log/nginx/error.log
2025/08/08 00:05:42 [error] 112824#112824: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 220.72.154.105, server: 43.201.70.73, request: "GET /admin/ HTTP/1.1", upstream: "http://127.0.0.1:8000/admin/", host: "43.201.70.73"
(venv) ubuntu@ip-172-26-9-152:~/deulbada_BE$ sudo tail -n 50 /var/log/daphne_deulbada_BE.log
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/utils.py", line 19, in import_by_path
    target = getattr(target, bit)
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config.asgi' has no attribute ''
Traceback (most recent call last):
  File "/home/ubuntu/deulbada_BE/venv/bin/daphne", line 8, in <module>
    sys.exit(CommandLineInterface.entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 171, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 239, in run
    application = self.load_asgi_app(args.application)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 208, in load_asgi_app
    return import_by_path(asgi_app_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/utils.py", line 19, in import_by_path
    target = getattr(target, bit)
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config.asgi' has no attribute ''
Traceback (most recent call last):
  File "/home/ubuntu/deulbada_BE/venv/bin/daphne", line 8, in <module>
    sys.exit(CommandLineInterface.entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 171, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 239, in run
    application = self.load_asgi_app(args.application)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 208, in load_asgi_app
    return import_by_path(asgi_app_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/utils.py", line 19, in import_by_path
    target = getattr(target, bit)
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config.asgi' has no attribute ''
2025-08-07 14:56:39,534 INFO     Starting server at tcp:port=8001:interface=0.0.0.0
2025-08-07 14:56:39,534 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2025-08-07 14:56:39,535 INFO     Configuring endpoint tcp:port=8001:interface=0.0.0.0
2025-08-07 14:56:39,535 INFO     Listening on TCP address 0.0.0.0:8001
2025-08-07 15:17:15,500 INFO     Killed 0 pending application instances
2025-08-07 15:17:16,292 INFO     Starting server at tcp:port=8001:interface=0.0.0.0
2025-08-07 15:17:16,293 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2025-08-07 15:17:16,293 INFO     Configuring endpoint tcp:port=8001:interface=0.0.0.0
2025-08-07 15:17:16,293 INFO     Listening on TCP address 0.0.0.0:8001
2025-08-07 15:26:30,097 INFO     Killed 0 pending application instances
2025-08-07 15:28:59,806 INFO     Starting server at tcp:port=8001:interface=0.0.0.0
2025-08-07 15:28:59,807 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2025-08-07 15:28:59,807 INFO     Configuring endpoint tcp:port=8001:interface=0.0.0.0
2025-08-07 15:28:59,807 INFO     Listening on TCP address 0.0.0.0:8001